/**
 * Interface representing the security aspects of two-factor authentication.
 * @export _ISecurity
 * @interface _ISecurity
 * @namespace IAuth._ITwoFactor._ISecurity
 * @description 
 * Defines the structure for two-factor authentication security, including the verification code.
 * This interface provides the necessary properties to handle 2FA code verification securely.
 * 
 * Key features:
 * - Stores 6-digit numeric verification code
 * - Enforces code length and range constraints
 * - Provides type safety for 2FA verification
 * 
 * @property {number} code_2fa - The two-factor authentication code (6 digits)
 * @since 2.0.0
 * @category Authentication
 * @module TwoFactor
 * @public
 * @see {@link IAuth.ITwoFactor._IAuth} For complete 2FA state management
 * 
 * @example
 * ```typescript
 * const security: _ISecurity = {
 *   code_2fa: 123456
 * };
 * ```
 */
export interface _ISecurity {
    /**
     * The two-factor authentication code
     * @type {number}
     * @description 
     * A 6-digit numeric code used for verifying the user's identity in two-factor authentication.
     * This code is typically generated by an authenticator app or sent via SMS/email.
     * Must be between 100000 and 999999 to ensure 6-digit length.
     * 
     * @property {number} code_2fa - The two-factor authentication code
     * @memberof _ISecurity
     * @required
     * @since 2.0.0
     * @example 123456
     * @minLength 6
     * @maxLength 6
     * @minimum 100000
     * @maximum 999999
     * @throws {ValidationError} If code is not a 6-digit number
     * @security This code should be kept secure and never exposed publicly
     */
    code_2fa: number;
}